# Problem 1 

In [ ]:
# 1 - numpy kütüphanesini import edin

# 2 - 5 elemanlı bir numpy array oluşturun

# 3 - Oluşturduğunuz arrayi küçükten büyüğe sıralayın.


In [2]:
import numpy as np
a=np.array([5,4,3,2,1])
a.sort()
a

array([1, 2, 3, 4, 5])

# Problem 2

In [37]:
# 1- (10,15,30,45,60) değerlerine sahip numpy dizisi oluşturunuz.
n=np.array([10,15,30,45,60])
print(n)
# 2- (5-15) arasındaki sayılarla numpy dizisi oluşturunuz.
k=np.arange(5,15) 
print(k)
# 3- (50-100) arasında 5'er 5'er artarak numpy dizisi oluşturunuz.
p=np.arange(50,100,5) 
print(p)
# 4- 10 elemanlı sıfırlardan oluşan bir dizi oluşturunuz.
o=np.zeros(10)
print(o)
# 5- 10 elemanlı birlerden oluşan bir dizi oluşturunuz.
l=np.ones(10)
print(l)
# 6- (0-100) arasında eşit aralıklı 5 sayı üretin.
b=np.linspace(0,100,5)
print(b)
# 7- (10-30) arasında rastgele 5 tane tamsayı üretin.
r=np.random.randint(10,30,5)
print(r)
# 8- [-1 ile 1] arasında 10 adet sayı üretin.
s=np.random.randint(-1,1,10)
print(s)
# 9- (3x5) boyutlarında (10-50) arasında rastgele bir matris oluşturunuz.
d=np.random.randint(10,50,(3,5))
print(d)
# 10- Üretilen matrisin satır ve sütun sayıları toplamlarını hesaplayınız ?
t1=np.sum(d,axis=0)
print(t1)
t2=np.sum(d,axis=1)
print(t2)
# 11- Üretilen matrisin en büyük, en küçük ve ortalaması nedir ?
maxi=d.max()
print(maxi)
mini=d.min()
print(mini)
ort=d.mean()
print(ort)
# 12- Üretilen matrisin en büyük değerinin indeksi kaçtır ?
m=d.argmax()
print(m)
# 13- (10-20) arasındaki sayıları içeren dizinin ilk 3 elemanını seçiniz.
y=np.arange(10,20)
print(y[:3])
# 14- Üretilen dizinin elemanlarını tersten yazdırın.
print(d[::-1])

# 15- Üretilen matrisin ilk satırını seçiniz.
print(d[0,:])

# 16- Üretilen matrisin 2.satır 3.sütundaki elemanı hangisidir ?
print(d[1:2,2:3])

# 17- Üretilen matrisin tüm satırlardaki ilk elemanı seçiniz.
print(d[:,0])

# 18- Üretilen matrisin her bir elemanının karesini alınız.
print(np.power(d,2))

# 19- Üretilen matris elemanlarının hangisi pozitif çift sayıdır ? Aralığı (-50,+50) arasında yapınız.
a=np.arange(-50,50)
print(a[a>0])

[10 15 30 45 60]
[ 5  6  7  8  9 10 11 12 13 14]
[50 55 60 65 70 75 80 85 90 95]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[  0.  25.  50.  75. 100.]
[12 19 28 15 19]
[ 0  0  0 -1  0  0  0  0 -1 -1]
[[43 21 14 33 44]
 [14 19 29 41 39]
 [10 29 15 30 24]]
[ 67  69  58 104 107]
[155 142 108]
44
10
27.0
4
[10 11 12]
[[10 29 15 30 24]
 [14 19 29 41 39]
 [43 21 14 33 44]]
[43 21 14 33 44]
[[29]]
[43 14 10]
[[1849  441  196 1089 1936]
 [ 196  361  841 1681 1521]
 [ 100  841  225  900  576]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49]
