# Problem 1

In [ ]:
# 1 - numpy kütüphanesini import edin

# 2 - 0 ile 10 arasında 5 sayıdan oluşan matris üretin

# 3 - matris'in boyutunu öğrenin

# 4 - matris'i yeniden boyutlandırın

# 5 - matris'in boyut sayısını öğrenin


In [12]:
import numpy as np
a=np.random.randint(10,size=5)
print(a)
print(a.shape)
print(a.reshape(5,1))
print(a.ndim)

[3 8 5 6 3]
(5,)
[[3]
 [8]
 [5]
 [6]
 [3]]
1


# Problem 2

In [ ]:
# 1 - 0 ile 10 arasında bulunan tek sayılardan oluşan matris üretin

# 2 - Oluşturduğunuz matrisi parçalayın

# 3 - Parçalanmış matrisleri birleştirin


In [20]:
x=np.arange(0,10)
y=x[x%2==1]
print(y)
z=np.split(y,[2,4])
print(z)
np.concatenate(z)

[1 3 5 7 9]
[array([1, 3]), array([5, 7]), array([9])]


array([1, 3, 5, 7, 9])

# Problem 3

In [ ]:
# 1 - 5 ile 100 arasında ikişer ikişer atlayarak rastgele 10 sayıdan oluşan matris üretin

# 2 - matris'in özelliklerini inceleyin


In [25]:
b=np.random.randint(5,100,size=10)
b[::]
b[::2]

array([26, 71,  9, 67, 80])

In [35]:
import random
print(random.randrange(5,100,2))

47
